### ISSUE TITLE
location_aware_upsampling_forward

### ISSUE THREAD

**Issue by zhukaii** [HolmesShuan/Location-aware-Upsampling-for-Semantic-Segmentation#1]
Where is the ‘LAU.location_aware_upsampling_forward’ in location_aware_upsampling_func.py please?

**Comment by HolmesShuan** [comment]
Please refer to [location_aware_upsampling.h](https://github.com/HolmesShuan/Location-aware-Upsampling-for-Semantic-Segmentation/blob/b46de243b125003f2465fe0be5e81533437fe0d5/LaU/src/location_aware_upsampling.h#L8).

**Comment by zhukaii** [comment]
Oh, thanks!
