### ISSUE TITLE
Con't find the LAU

### ISSUE THREAD

**Issue by Dorispaopao** [HolmesShuan/Location-aware-Upsampling-for-Semantic-Segmentation#4]
How to import the LAU which contains" LAU.location_determined_upsampling_forward"?

**Comment by HolmesShuan** [comment]
Thanks for your interest. Please refer to [https://github.com/HolmesShuan/Location-aware-Upsampling-for-Semantic-Segmentation/blob/83822e86570bbff4ca721d80089b5d82f1958852/LaU/test.py#L55](https://github.com/HolmesShuan/Location-aware-Upsampling-for-Semantic-Segmentation/blob/83822e86570bbff4ca721d80089b5d82f1958852/LaU/test.py#L55)
